spring:
  profiles:
    active: local

---

spring:
  profiles: local
  kafka:
    topic: library-events
#    template:
#      default-topic: library-events
    producer:
      retries: 10
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


