spring:
  profiles:
    active: local
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      topic: test-topic
      group-id: test-topic
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        session.timeout.ms: 15000
        ssl:
          endpoint:
            identification:
              algorithm:
        value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    retry:
      generate-alert-retry-threshold: 3
      backoff:
        initial-interval: 3000 #3seconds
        max-interval: 60000 #60seconds
    listener:
      poll-timeout: 3000
      concurrency: 1
      ack-mode: manual
server:
  port: 8090
  main:
    allow-bean-definition-overriding: true
