spring:
  profiles:
    active: local
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      topic: test-topic
      group-id: my-first-topic-group
      auto-offset-reset: latest
      enable-auto-commit: false
      properties:
        session.timeout.ms: 15000
        ssl:
          endpoint:
            identification:
              algorithm:
        value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      poll-timeout: 3000
      concurrency: 1
      ack-mode: manual
server:
  port: 8081
  main:
    allow-bean-definition-overriding: true
